apiVersion: kuttl.dev/v1beta1
kind: TestAssert
timeout: 600
collectors:
- type: command
  command: oc logs -n openstack-operators -l openstack.org/operator-name=openstack
  name: operator-logs
---
apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app: openstackansibleee
    openstackdataplanedeployment: edpm-compute-no-nodes
    openstackdataplanenodeset: edpm-compute-no-nodes
    openstackdataplaneservice: failed-service
  name: failed-service-edpm-compute-no-nodes-edpm-compute-no-nodes
  namespace: openstack-kuttl-tests
  ownerReferences:
  - apiVersion: dataplane.openstack.org/v1beta1
    blockOwnerDeletion: true
    controller: true
    kind: OpenStackDataPlaneDeployment
    name: edpm-compute-no-nodes
spec:
  backoffLimit: 3
  completionMode: NonIndexed
  completions: 1
  manualSelector: false
  parallelism: 1
  podReplacementPolicy: TerminatingOrFailed
  suspend: false
  template:
    metadata:
      annotations:
        k8s.v1.cni.cncf.io/networks: '[]'
      creationTimestamp: null
      labels:
        app: openstackansibleee
        batch.kubernetes.io/job-name: failed-service-edpm-compute-no-nodes-edpm-compute-no-nodes
        openstackdataplanedeployment: edpm-compute-no-nodes
        openstackdataplanenodeset: edpm-compute-no-nodes
        openstackdataplaneservice: failed-service
    spec:
      containers:
      - args:
        - ansible-runner
        - run
        - /runner
        - -p
        - playbook.yaml
        - -i
        - failed-service-edpm-compute-no-nodes-edpm-compute-no-nodes
        env:
        - name: ANSIBLE_FORCE_COLOR
          value: "True"
        - name: RUNNER_PLAYBOOK
          value: |2+

            - hosts: localhost
              gather_facts: no
              name: kuttl play
              tasks:
                - name: Copy absent file
                  ansible.builtin.shell: |
                      set -euxo pipefail
                      cp absent failed_op


        - name: RUNNER_EXTRA_VARS
          value: |2+

            edpm_override_hosts: edpm-compute-no-nodes
            edpm_service_type: failed-service


        imagePullPolicy: Always
        name: failed-service-edpm-compute-no-nodes-edpm-compute-no-nodes
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/lib/openstack/cacerts/failed-service
          name: failed-service-combined-ca-bundle
        - mountPath: /runner/env/ssh_key
          name: ssh-key
          subPath: ssh_key
        - mountPath: /runner/inventory/hosts
          name: inventory
          subPath: inventory
      dnsPolicy: ClusterFirst
      restartPolicy: Never
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: edpm-compute-no-nodes
      serviceAccountName: edpm-compute-no-nodes
      terminationGracePeriodSeconds: 30
      volumes:
      - name: failed-service-combined-ca-bundle
        secret:
          defaultMode: 420
          secretName: combined-ca-bundle
      - name: ssh-key
        secret:
          defaultMode: 420
          items:
          - key: ssh-privatekey
            path: ssh_key
          secretName: dataplane-ansible-ssh-private-key-secret
      - name: inventory
        secret:
          defaultMode: 420
          items:
          - key: inventory
            path: inventory
          secretName: dataplanenodeset-edpm-compute-no-nodes
status:
  failed: 4
---
apiVersion: dataplane.openstack.org/v1beta1
kind: OpenStackDataPlaneNodeSet
metadata:
  generation: 1
  name: edpm-compute-no-nodes
  namespace: openstack-kuttl-tests
spec:
  nodeTemplate:
    ansibleSSHPrivateKeySecret: dataplane-ansible-ssh-private-key-secret
    managementNetwork: ctlplane
  nodes: {}
  preProvisioned: true
  services:
  - failed-service
  tlsEnabled: true
status:
  conditions:
  - message: 'Deployment error occurred in failed-service service error backoff limit
      reached for execution.name failed-service-edpm-compute-no-nodes-edpm-compute-no-nodes
      execution.namespace openstack-kuttl-tests execution.condition.message: Job has reached the specified backoff limit'
    reason: Error
    severity: Error
    status: "False"
    type: Ready
  - message: 'Deployment error occurred in failed-service service error backoff limit
      reached for execution.name failed-service-edpm-compute-no-nodes-edpm-compute-no-nodes
      execution.namespace openstack-kuttl-tests execution.condition.message: Job has reached the specified backoff limit'
    reason: Error
    severity: Error
    status: "False"
    type: DeploymentReady
  - message: Input data complete
    reason: Ready
    status: "True"
    type: InputReady
  - message: NodeSetDNSDataReady ready
    reason: Ready
    status: "True"
    type: NodeSetDNSDataReady
  - message: NodeSetIPReservationReady ready
    reason: Ready
    status: "True"
    type: NodeSetIPReservationReady
  - message: ServiceAccount created
    reason: Ready
    status: "True"
    type: ServiceAccountReady
  - message: Setup complete
    reason: Ready
    status: "True"
    type: SetupReady
  deploymentStatuses:
    edpm-compute-no-nodes:
    - message: 'Deployment error occurred in failed-service service error backoff
        limit reached for execution.name failed-service-edpm-compute-no-nodes-edpm-compute-no-nodes
        execution.namespace openstack-kuttl-tests execution.condition.message: Job has reached the specified backoff limit'
      reason: BackoffLimitExceeded
      severity: Error
      status: "False"
      type: NodeSetDeploymentReady
    - message: 'Deployment error occurred in failed-service service error backoff
        limit reached for execution.name failed-service-edpm-compute-no-nodes-edpm-compute-no-nodes
        execution.namespace openstack-kuttl-tests execution.condition.message: Job has reached the specified backoff limit'
      reason: BackoffLimitExceeded
      severity: Error
      status: "False"
      type: ServiceFailedServiceDeploymentReady
  observedGeneration: 1
---
apiVersion: dataplane.openstack.org/v1beta1
kind: OpenStackDataPlaneDeployment
metadata:
  generation: 1
  name: edpm-compute-no-nodes
  namespace: openstack-kuttl-tests
spec:
  backoffLimit: 3
  deploymentRequeueTime: 15
  nodeSets:
  - edpm-compute-no-nodes
status:
  conditions:
  - message: 'Deployment error occurred nodeSet: edpm-compute-no-nodes error: backoff
      limit reached for execution.name failed-service-edpm-compute-no-nodes-edpm-compute-no-nodes
      execution.namespace openstack-kuttl-tests execution.condition.message: Job has reached the specified backoff limit'
    reason: BackoffLimitExceeded
    severity: Error
    status: "False"
    type: Ready
  - message: 'Deployment error occurred nodeSet: edpm-compute-no-nodes error: backoff
      limit reached for execution.name failed-service-edpm-compute-no-nodes-edpm-compute-no-nodes
      execution.namespace openstack-kuttl-tests execution.condition.message: Job has reached the specified backoff limit'
    reason: BackoffLimitExceeded
    severity: Error
    status: "False"
    type: DeploymentReady
  - message: Input data complete
    reason: Ready
    status: "True"
    type: InputReady
  nodeSetConditions:
    edpm-compute-no-nodes:
    - message: 'Deployment error occurred in failed-service service error backoff
        limit reached for execution.name failed-service-edpm-compute-no-nodes-edpm-compute-no-nodes
        execution.namespace openstack-kuttl-tests execution.condition.message: Job has reached the specified backoff limit'
      reason: BackoffLimitExceeded
      severity: Error
      status: "False"
      type: NodeSetDeploymentReady
    - message: 'Deployment error occurred in failed-service service error backoff
        limit reached for execution.name failed-service-edpm-compute-no-nodes-edpm-compute-no-nodes
        execution.namespace openstack-kuttl-tests execution.condition.message: Job has reached the specified backoff limit'
      reason: BackoffLimitExceeded
      severity: Error
      status: "False"
      type: ServiceFailedServiceDeploymentReady
  observedGeneration: 1
